"$schema" = "https://starship.rs/config-schema.json"
format = "$username$hostname$directory$character"
right_format = "$all${env_var.ZMX_SESSION}"
continuation_prompt = "[∙](bright-black) "
scan_timeout = 30
command_timeout = 1000
add_newline = false

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
disabled = false

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "yellow bold"
show_milliseconds = false
disabled = false
show_notifications = false
min_time_to_notify = 45000

[hostname]
ssh_only = false
ssh_symbol = "🌐 "
trim_at = "."
format = "[$ssh_symbol$hostname]($style) "
style = "green dimmed bold"
disabled = false

[username]
format = "[$user]($style) at "
style_root = "red bold"
style_user = "yellow bold"
show_always = true
disabled = false

[env_var.ZMX_SESSION]
symbol = "💬 "
format = "in [$symbol$env_value]($style) "
description = "zmx session name"
style = "bold magenta"
